version: "3.9"

services:
  app:
    build: .
    restart: always
    entrypoint: ./bin/entrypoint.sh
    depends_on:
      - redis
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
      RD_DB: 5
      RD_HOST: redis
      RD_PORT: 6379
  redis:
    image: redis
    volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  logs:
  mongo_db:
    external: true