version: "3.9"

services:
  app:
    build: .
    restart: always
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:alpine
    restart: unless-stopped
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: