[project]
name = "aiogram-mongo-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.22.0",
    "babel>=2.17.0",
    "beanie>=2.0.0",
    "environs>=14.3.0",
    "loguru>=0.7.3",
    "pymongo>=4.14.1",
    "pytz>=2025.2",
    "redis>=6.4.0",
]
