[tool.poetry]
name = "aiogram-mongo-template"
version = "0.1.0"
description = ""
authors = ["WebShining <artemilienkono@gmail.com>"]
readme = "README.md"
packages = [{include = "aiogram_mongo_template"}]

[tool.poetry.dependencies]
python = "^3.10"
environs = "^9.5.0"
pymongo = "^4.2.0"
aiogram = "^2.22.1"
loguru = "^0.6.0"
aioredis = "^2.0.1"
pydantic = "^1.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
